POST http://localhost:3333/goal
Content-Type: application/json

{
    "title":"praticar matematica",
    "desiredWeeklyFrequency":3
}

###

GET http://localhost:3333/pending-goals

###

POST http://localhost:3333/completions
Content-Type: application/json

{
    "goalId":"v1zl1kesfr1nerw3mjn519e5"
}
###
    
GET http://localhost:3333/summary