POST http://localhost:3333/goal
Content-Type: application/json

{
    "title":"Fazer alguma coisa",
    "desiredWeeklyFrequency":5
}

###

GET http://localhost:3333/pending-goals

###

POST http://localhost:3333/completions
Content-Type: application/json

{
    "goalId":"l1dvstnogz6qqu7u7zdfvtf9"
}