POST http://localhost:3333/goal
Content-Type: application/json

{
    "title":"praticar matematica",
    "desiredWeeklyFrequency":3,

}

###

GET http://localhost:3333/pending-goals

###

POST http://localhost:3333/completions
Content-Type: application/json

{
    "goalId":"o2vgqnj1fc87he0w03phaq63",
    "createAt":1695859200
}
###
    
GET http://localhost:3333/summary